
// This file has been generated by the GUI designer. Do not modify.
namespace Chrono
{
	public partial class WatchConfigWindow
	{
		private global::Gtk.Alignment alignment1;
		private global::Gtk.VBox vbox2;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Label label2;
		private global::Gtk.ComboBoxEntry watchNameCombo;
		private global::Gtk.Button newBtn;
		private global::Gtk.Notebook detailBook;
		private global::Gtk.Alignment alignment2;
		private global::Gtk.VBox vbox4;
		private global::Gtk.Frame frame2;
		private global::Gtk.Alignment GtkAlignment1;
		private global::Gtk.Table table1;
		private global::Gtk.Alignment alignment3;
		private global::Gtk.Button setCountingBtn;
		private global::Gtk.HBox hbox6;
		private global::Gtk.Label label3;
		private global::Gtk.SpinButton speedEntry;
		private global::Gtk.RadioButton radioBackward;
		private global::Gtk.RadioButton radioForward;
		private global::Gtk.Label GtkLabel7;
		private global::Gtk.Frame frame1;
		private global::Gtk.Alignment GtkAlignment;
		private global::Gtk.HBox hbox7;
		private global::Gtk.CheckButton logStartsCheck;
		private global::Gtk.CheckButton logStopsCheck;
		private global::Gtk.Label GtkLabel6;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Button deleteWatchBtn;
		private global::Gtk.Button showWatchBtn;
		private global::Gtk.Label label1;
		private global::Gtk.HButtonBox hbuttonbox2;
		private global::Gtk.Button closeBtn;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Chrono.WatchConfigWindow
			this.Name = "Chrono.WatchConfigWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Stopwatch Configuration");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("icon.ico");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.AllowGrow = false;
			// Container child Chrono.WatchConfigWindow.Gtk.Container+ContainerChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.alignment1.LeftPadding = ((uint)(6));
			this.alignment1.TopPadding = ((uint)(6));
			this.alignment1.RightPadding = ((uint)(6));
			this.alignment1.BottomPadding = ((uint)(6));
			// Container child alignment1.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Watch");
			this.hbox1.Add (this.label2);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label2]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.watchNameCombo = global::Gtk.ComboBoxEntry.NewText ();
			this.watchNameCombo.Name = "watchNameCombo";
			this.hbox1.Add (this.watchNameCombo);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.watchNameCombo]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.newBtn = new global::Gtk.Button ();
			this.newBtn.CanFocus = true;
			this.newBtn.Name = "newBtn";
			this.newBtn.UseUnderline = true;
			this.newBtn.Label = global::Mono.Unix.Catalog.GetString ("New");
			this.hbox1.Add (this.newBtn);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.newBtn]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.detailBook = new global::Gtk.Notebook ();
			this.detailBook.CanFocus = true;
			this.detailBook.Name = "detailBook";
			this.detailBook.CurrentPage = 0;
			this.detailBook.BorderWidth = ((uint)(1));
			// Container child detailBook.Gtk.Notebook+NotebookChild
			this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			this.alignment2.LeftPadding = ((uint)(6));
			this.alignment2.TopPadding = ((uint)(3));
			this.alignment2.RightPadding = ((uint)(6));
			this.alignment2.BottomPadding = ((uint)(3));
			// Container child alignment2.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(6));
			this.GtkAlignment1.TopPadding = ((uint)(3));
			this.GtkAlignment1.RightPadding = ((uint)(6));
			this.GtkAlignment1.BottomPadding = ((uint)(3));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.alignment3 = new global::Gtk.Alignment (1F, 0.5F, 1F, 1F);
			this.alignment3.Name = "alignment3";
			this.alignment3.LeftPadding = ((uint)(60));
			// Container child alignment3.Gtk.Container+ContainerChild
			this.setCountingBtn = new global::Gtk.Button ();
			this.setCountingBtn.CanFocus = true;
			this.setCountingBtn.Name = "setCountingBtn";
			this.setCountingBtn.UseUnderline = true;
			this.setCountingBtn.Label = global::Mono.Unix.Catalog.GetString ("Set");
			this.alignment3.Add (this.setCountingBtn);
			this.table1.Add (this.alignment3);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment3]));
			w6.TopAttach = ((uint)(1));
			w6.BottomAttach = ((uint)(2));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Speed");
			this.hbox6.Add (this.label3);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label3]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.speedEntry = new global::Gtk.SpinButton (0D, 60D, 1D);
			this.speedEntry.CanFocus = true;
			this.speedEntry.Name = "speedEntry";
			this.speedEntry.Adjustment.PageIncrement = 5D;
			this.speedEntry.ClimbRate = 1D;
			this.speedEntry.Digits = ((uint)(1));
			this.speedEntry.Numeric = true;
			this.speedEntry.Value = 1D;
			this.hbox6.Add (this.speedEntry);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.speedEntry]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.table1.Add (this.hbox6);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.hbox6]));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.radioBackward = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Backward"));
			this.radioBackward.CanFocus = true;
			this.radioBackward.Name = "radioBackward";
			this.radioBackward.DrawIndicator = true;
			this.radioBackward.UseUnderline = true;
			this.radioBackward.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.table1.Add (this.radioBackward);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.radioBackward]));
			w10.TopAttach = ((uint)(1));
			w10.BottomAttach = ((uint)(2));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.radioForward = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Forward"));
			this.radioForward.CanFocus = true;
			this.radioForward.Name = "radioForward";
			this.radioForward.DrawIndicator = true;
			this.radioForward.UseUnderline = true;
			this.radioForward.Group = this.radioBackward.Group;
			this.table1.Add (this.radioForward);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.radioForward]));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment1.Add (this.table1);
			this.frame2.Add (this.GtkAlignment1);
			this.GtkLabel7 = new global::Gtk.Label ();
			this.GtkLabel7.Name = "GtkLabel7";
			this.GtkLabel7.LabelProp = global::Mono.Unix.Catalog.GetString ("Counting");
			this.GtkLabel7.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel7;
			this.vbox4.Add (this.frame2);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.frame2]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(6));
			this.GtkAlignment.TopPadding = ((uint)(3));
			this.GtkAlignment.RightPadding = ((uint)(6));
			this.GtkAlignment.BottomPadding = ((uint)(3));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.logStartsCheck = new global::Gtk.CheckButton ();
			this.logStartsCheck.TooltipMarkup = "Uncheck this to stop logging when the stopwatch starts";
			this.logStartsCheck.CanFocus = true;
			this.logStartsCheck.Name = "logStartsCheck";
			this.logStartsCheck.Label = global::Mono.Unix.Catalog.GetString ("Starts");
			this.logStartsCheck.Active = true;
			this.logStartsCheck.DrawIndicator = true;
			this.logStartsCheck.UseUnderline = true;
			this.hbox7.Add (this.logStartsCheck);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.logStartsCheck]));
			w15.Position = 0;
			// Container child hbox7.Gtk.Box+BoxChild
			this.logStopsCheck = new global::Gtk.CheckButton ();
			this.logStopsCheck.TooltipMarkup = "Uncheck this to stop logging when the stopwatch stops";
			this.logStopsCheck.CanFocus = true;
			this.logStopsCheck.Name = "logStopsCheck";
			this.logStopsCheck.Label = global::Mono.Unix.Catalog.GetString ("Stops");
			this.logStopsCheck.Active = true;
			this.logStopsCheck.DrawIndicator = true;
			this.logStopsCheck.UseUnderline = true;
			this.hbox7.Add (this.logStopsCheck);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.logStopsCheck]));
			w16.Position = 1;
			this.GtkAlignment.Add (this.hbox7);
			this.frame1.Add (this.GtkAlignment);
			this.GtkLabel6 = new global::Gtk.Label ();
			this.GtkLabel6.Name = "GtkLabel6";
			this.GtkLabel6.LabelProp = global::Mono.Unix.Catalog.GetString ("Log");
			this.GtkLabel6.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel6;
			this.vbox4.Add (this.frame1);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.frame1]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.deleteWatchBtn = new global::Gtk.Button ();
			this.deleteWatchBtn.CanFocus = true;
			this.deleteWatchBtn.Name = "deleteWatchBtn";
			this.deleteWatchBtn.UseUnderline = true;
			this.deleteWatchBtn.Label = global::Mono.Unix.Catalog.GetString ("Delete");
			this.hbox2.Add (this.deleteWatchBtn);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.deleteWatchBtn]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.showWatchBtn = new global::Gtk.Button ();
			this.showWatchBtn.CanFocus = true;
			this.showWatchBtn.Name = "showWatchBtn";
			this.showWatchBtn.UseUnderline = true;
			this.showWatchBtn.Label = global::Mono.Unix.Catalog.GetString ("Show");
			this.hbox2.Add (this.showWatchBtn);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.showWatchBtn]));
			w21.PackType = ((global::Gtk.PackType)(1));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			this.vbox4.Add (this.hbox2);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox2]));
			w22.Position = 2;
			w22.Expand = false;
			w22.Fill = false;
			this.alignment2.Add (this.vbox4);
			this.detailBook.Add (this.alignment2);
			// Notebook tab
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("General");
			this.detailBook.SetTabLabel (this.alignment2, this.label1);
			this.label1.ShowAll ();
			this.vbox2.Add (this.detailBook);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.detailBook]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbuttonbox2 = new global::Gtk.HButtonBox ();
			this.hbuttonbox2.Name = "hbuttonbox2";
			this.hbuttonbox2.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.closeBtn = new global::Gtk.Button ();
			this.closeBtn.CanFocus = true;
			this.closeBtn.Name = "closeBtn";
			this.closeBtn.UseUnderline = true;
			this.closeBtn.Label = global::Mono.Unix.Catalog.GetString ("Close");
			this.hbuttonbox2.Add (this.closeBtn);
			global::Gtk.ButtonBox.ButtonBoxChild w26 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.closeBtn]));
			w26.Expand = false;
			w26.Fill = false;
			this.vbox2.Add (this.hbuttonbox2);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbuttonbox2]));
			w27.Position = 2;
			w27.Expand = false;
			w27.Fill = false;
			this.alignment1.Add (this.vbox2);
			this.Add (this.alignment1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 300;
			this.DefaultHeight = 303;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.windowDelete_event);
			this.newBtn.Clicked += new global::System.EventHandler (this.newBtn_event);
			this.setCountingBtn.Clicked += new global::System.EventHandler (this.setSpeedClicked_event);
			this.logStartsCheck.Toggled += new global::System.EventHandler (this.logStartsToggled_event);
			this.logStopsCheck.Toggled += new global::System.EventHandler (this.logStopsToggled_event);
			this.deleteWatchBtn.Clicked += new global::System.EventHandler (this.deleteWatch_event);
			this.showWatchBtn.Clicked += new global::System.EventHandler (this.showWatch_event);
			this.closeBtn.Clicked += new global::System.EventHandler (this.closeWindow_event);
		}
	}
}
