
// This file has been generated by the GUI designer. Do not modify.
namespace Chrono
{
	public partial class ClockPropertiesWindow
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Label label2;
		private global::Gtk.ComboBoxEntry clockNameBox;
		private global::Gtk.Button clockNameBtn;
		private global::Gtk.Notebook detailBook;
		private global::Gtk.Alignment alignment1;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Frame frame2;
		private global::Gtk.Alignment GtkAlignment1;
		private global::Gtk.HBox hbox10;
		private global::Gtk.CheckButton logStartsCheck;
		private global::Gtk.CheckButton logStopsCheck;
		private global::Gtk.Label GtkLabel3;
		private global::Gtk.Frame frame4;
		private global::Gtk.Alignment GtkAlignment3;
		private global::Gtk.HBox hbox9;
		private global::Gtk.VBox vbox9;
		private global::Gtk.RadioButton tickForwardOption;
		private global::Gtk.RadioButton tickBackwardOption;
		private global::Gtk.VBox vbox12;
		private global::Gtk.HBox hbox7;
		private global::Gtk.SpinButton speedEntry;
		private global::Gtk.Label label4;
		private global::Gtk.Button button14;
		private global::Gtk.Label GtkLabel13;
		private global::Gtk.Frame frame3;
		private global::Gtk.Alignment GtkAlignment2;
		private global::Gtk.HBox hbox2;
		private global::Gtk.VBox vbox10;
		private global::Gtk.RadioButton normalWindowOption;
		private global::Gtk.RadioButton compactWindowOption;
		private global::Gtk.VBox vbox4;
		private global::Gtk.CheckButton onTopCheck;
		private global::Gtk.ToggleButton displayStopwatchBtn;
		private global::Gtk.Label GtkLabel11;
		private global::Gtk.HButtonBox hbuttonbox3;
		private global::Gtk.Button deleteBtn;
		private global::Gtk.Label label;
		private global::Gtk.HSeparator hseparator2;
		private global::Gtk.HButtonBox hbuttonbox2;
		private global::Gtk.Button closeBtn;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Chrono.ClockPropertiesWindow
			this.Name = "Chrono.ClockPropertiesWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Stopwatch Properties");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("Chrono.icon.ico");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(6));
			this.Resizable = false;
			this.AllowGrow = false;
			// Container child Chrono.ClockPropertiesWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Clock");
			this.hbox1.Add (this.label2);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label2]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.clockNameBox = new global::Gtk.ComboBoxEntry ();
			this.clockNameBox.Name = "clockNameBox";
			this.hbox1.Add (this.clockNameBox);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.clockNameBox]));
			w2.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.clockNameBtn = new global::Gtk.Button ();
			this.clockNameBtn.WidthRequest = 80;
			this.clockNameBtn.CanDefault = true;
			this.clockNameBtn.CanFocus = true;
			this.clockNameBtn.Name = "clockNameBtn";
			this.clockNameBtn.UseUnderline = true;
			this.clockNameBtn.Label = global::Mono.Unix.Catalog.GetString ("Create");
			this.hbox1.Add (this.clockNameBtn);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.clockNameBtn]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.detailBook = new global::Gtk.Notebook ();
			this.detailBook.CanFocus = true;
			this.detailBook.Name = "detailBook";
			this.detailBook.CurrentPage = 0;
			this.detailBook.BorderWidth = ((uint)(1));
			// Container child detailBook.Gtk.Notebook+NotebookChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.alignment1.LeftPadding = ((uint)(4));
			this.alignment1.TopPadding = ((uint)(2));
			this.alignment1.RightPadding = ((uint)(4));
			this.alignment1.BottomPadding = ((uint)(4));
			// Container child alignment1.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			this.GtkAlignment1.TopPadding = ((uint)(3));
			this.GtkAlignment1.RightPadding = ((uint)(6));
			this.GtkAlignment1.BottomPadding = ((uint)(3));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.hbox10 = new global::Gtk.HBox ();
			this.hbox10.Name = "hbox10";
			this.hbox10.Homogeneous = true;
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.logStartsCheck = new global::Gtk.CheckButton ();
			this.logStartsCheck.CanFocus = true;
			this.logStartsCheck.Name = "logStartsCheck";
			this.logStartsCheck.Label = global::Mono.Unix.Catalog.GetString ("Starts");
			this.logStartsCheck.DrawIndicator = true;
			this.logStartsCheck.UseUnderline = true;
			this.hbox10.Add (this.logStartsCheck);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.logStartsCheck]));
			w5.Position = 0;
			// Container child hbox10.Gtk.Box+BoxChild
			this.logStopsCheck = new global::Gtk.CheckButton ();
			this.logStopsCheck.CanFocus = true;
			this.logStopsCheck.Name = "logStopsCheck";
			this.logStopsCheck.Label = global::Mono.Unix.Catalog.GetString ("Stops");
			this.logStopsCheck.DrawIndicator = true;
			this.logStopsCheck.UseUnderline = true;
			this.hbox10.Add (this.logStopsCheck);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.logStopsCheck]));
			w6.Position = 1;
			this.GtkAlignment1.Add (this.hbox10);
			this.frame2.Add (this.GtkAlignment1);
			this.GtkLabel3 = new global::Gtk.Label ();
			this.GtkLabel3.Name = "GtkLabel3";
			this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString ("Log");
			this.frame2.LabelWidget = this.GtkLabel3;
			this.vbox3.Add (this.frame2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.frame2]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.frame4 = new global::Gtk.Frame ();
			this.frame4.Name = "frame4";
			// Container child frame4.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			this.GtkAlignment3.TopPadding = ((uint)(3));
			this.GtkAlignment3.RightPadding = ((uint)(6));
			this.GtkAlignment3.BottomPadding = ((uint)(3));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.vbox9 = new global::Gtk.VBox ();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.tickForwardOption = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Forward"));
			this.tickForwardOption.CanFocus = true;
			this.tickForwardOption.Name = "tickForwardOption";
			this.tickForwardOption.DrawIndicator = true;
			this.tickForwardOption.UseUnderline = true;
			this.tickForwardOption.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.vbox9.Add (this.tickForwardOption);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.tickForwardOption]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.tickBackwardOption = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Backward"));
			this.tickBackwardOption.CanFocus = true;
			this.tickBackwardOption.Name = "tickBackwardOption";
			this.tickBackwardOption.DrawIndicator = true;
			this.tickBackwardOption.UseUnderline = true;
			this.tickBackwardOption.Group = this.tickForwardOption.Group;
			this.vbox9.Add (this.tickBackwardOption);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.tickBackwardOption]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			this.hbox9.Add (this.vbox9);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.vbox9]));
			w12.Position = 0;
			w12.Expand = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.vbox12 = new global::Gtk.VBox ();
			this.vbox12.Name = "vbox12";
			this.vbox12.Spacing = 6;
			// Container child vbox12.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.speedEntry = new global::Gtk.SpinButton (0D, 60D, 1D);
			this.speedEntry.CanFocus = true;
			this.speedEntry.Name = "speedEntry";
			this.speedEntry.Adjustment.PageIncrement = 6D;
			this.speedEntry.ClimbRate = 1D;
			this.speedEntry.Digits = ((uint)(2));
			this.speedEntry.Numeric = true;
			this.speedEntry.Value = 1D;
			this.hbox7.Add (this.speedEntry);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.speedEntry]));
			w13.PackType = ((global::Gtk.PackType)(1));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Speed");
			this.hbox7.Add (this.label4);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.label4]));
			w14.PackType = ((global::Gtk.PackType)(1));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			this.vbox12.Add (this.hbox7);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.hbox7]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox12.Gtk.Box+BoxChild
			this.button14 = new global::Gtk.Button ();
			this.button14.WidthRequest = 40;
			this.button14.CanFocus = true;
			this.button14.Name = "button14";
			this.button14.UseUnderline = true;
			this.button14.Label = global::Mono.Unix.Catalog.GetString ("Set");
			this.vbox12.Add (this.button14);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.button14]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			this.hbox9.Add (this.vbox12);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.vbox12]));
			w17.PackType = ((global::Gtk.PackType)(1));
			w17.Position = 1;
			w17.Expand = false;
			this.GtkAlignment3.Add (this.hbox9);
			this.frame4.Add (this.GtkAlignment3);
			this.GtkLabel13 = new global::Gtk.Label ();
			this.GtkLabel13.Name = "GtkLabel13";
			this.GtkLabel13.LabelProp = global::Mono.Unix.Catalog.GetString ("Ticking");
			this.frame4.LabelWidget = this.GtkLabel13;
			this.vbox3.Add (this.frame4);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.frame4]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.frame3 = new global::Gtk.Frame ();
			this.frame3.Name = "frame3";
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			this.GtkAlignment2.TopPadding = ((uint)(3));
			this.GtkAlignment2.RightPadding = ((uint)(6));
			this.GtkAlignment2.BottomPadding = ((uint)(3));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox10 = new global::Gtk.VBox ();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.normalWindowOption = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Normal"));
			this.normalWindowOption.CanFocus = true;
			this.normalWindowOption.Name = "normalWindowOption";
			this.normalWindowOption.DrawIndicator = true;
			this.normalWindowOption.UseUnderline = true;
			this.normalWindowOption.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.vbox10.Add (this.normalWindowOption);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.normalWindowOption]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.compactWindowOption = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Compact"));
			this.compactWindowOption.CanFocus = true;
			this.compactWindowOption.Name = "compactWindowOption";
			this.compactWindowOption.DrawIndicator = true;
			this.compactWindowOption.UseUnderline = true;
			this.compactWindowOption.Group = this.normalWindowOption.Group;
			this.vbox10.Add (this.compactWindowOption);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.compactWindowOption]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			this.hbox2.Add (this.vbox10);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox10]));
			w23.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.onTopCheck = new global::Gtk.CheckButton ();
			this.onTopCheck.CanFocus = true;
			this.onTopCheck.Name = "onTopCheck";
			this.onTopCheck.Label = global::Mono.Unix.Catalog.GetString ("Always Visible");
			this.onTopCheck.DrawIndicator = true;
			this.onTopCheck.UseUnderline = true;
			this.vbox4.Add (this.onTopCheck);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.onTopCheck]));
			w24.Position = 0;
			w24.Expand = false;
			w24.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.displayStopwatchBtn = new global::Gtk.ToggleButton ();
			this.displayStopwatchBtn.CanFocus = true;
			this.displayStopwatchBtn.Name = "displayStopwatchBtn";
			this.displayStopwatchBtn.UseUnderline = true;
			this.displayStopwatchBtn.Label = global::Mono.Unix.Catalog.GetString ("Display");
			this.vbox4.Add (this.displayStopwatchBtn);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.displayStopwatchBtn]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			this.hbox2.Add (this.vbox4);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox4]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			this.GtkAlignment2.Add (this.hbox2);
			this.frame3.Add (this.GtkAlignment2);
			this.GtkLabel11 = new global::Gtk.Label ();
			this.GtkLabel11.Name = "GtkLabel11";
			this.GtkLabel11.LabelProp = global::Mono.Unix.Catalog.GetString ("Stopwatch Window");
			this.frame3.LabelWidget = this.GtkLabel11;
			this.vbox3.Add (this.frame3);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.frame3]));
			w29.Position = 2;
			w29.Expand = false;
			w29.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbuttonbox3 = new global::Gtk.HButtonBox ();
			this.hbuttonbox3.Name = "hbuttonbox3";
			this.hbuttonbox3.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
			// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
			this.deleteBtn = new global::Gtk.Button ();
			this.deleteBtn.CanFocus = true;
			this.deleteBtn.Name = "deleteBtn";
			this.deleteBtn.UseUnderline = true;
			this.deleteBtn.Label = global::Mono.Unix.Catalog.GetString ("Delete");
			this.hbuttonbox3.Add (this.deleteBtn);
			global::Gtk.ButtonBox.ButtonBoxChild w30 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3 [this.deleteBtn]));
			w30.Expand = false;
			w30.Fill = false;
			this.vbox3.Add (this.hbuttonbox3);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbuttonbox3]));
			w31.PackType = ((global::Gtk.PackType)(1));
			w31.Position = 3;
			w31.Expand = false;
			w31.Fill = false;
			this.alignment1.Add (this.vbox3);
			this.detailBook.Add (this.alignment1);
			// Notebook tab
			this.label = new global::Gtk.Label ();
			this.label.Name = "label";
			this.label.LabelProp = global::Mono.Unix.Catalog.GetString ("General");
			this.detailBook.SetTabLabel (this.alignment1, this.label);
			this.label.ShowAll ();
			this.vbox2.Add (this.detailBook);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.detailBook]));
			w34.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator ();
			this.hseparator2.Name = "hseparator2";
			this.vbox2.Add (this.hseparator2);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hseparator2]));
			w35.Position = 2;
			w35.Expand = false;
			w35.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbuttonbox2 = new global::Gtk.HButtonBox ();
			this.hbuttonbox2.Name = "hbuttonbox2";
			this.hbuttonbox2.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.closeBtn = new global::Gtk.Button ();
			this.closeBtn.CanFocus = true;
			this.closeBtn.Name = "closeBtn";
			this.closeBtn.UseUnderline = true;
			this.closeBtn.Label = global::Mono.Unix.Catalog.GetString ("Close");
			this.hbuttonbox2.Add (this.closeBtn);
			global::Gtk.ButtonBox.ButtonBoxChild w36 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.closeBtn]));
			w36.Expand = false;
			w36.Fill = false;
			this.vbox2.Add (this.hbuttonbox2);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbuttonbox2]));
			w37.PackType = ((global::Gtk.PackType)(1));
			w37.Position = 3;
			w37.Expand = false;
			w37.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 332;
			this.DefaultHeight = 425;
			this.clockNameBtn.HasDefault = true;
			this.Hide ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.windowDelete_event);
			this.clockNameBox.Changed += new global::System.EventHandler (this.clockNameChanged_event);
			this.clockNameBtn.Clicked += new global::System.EventHandler (this.clockNameBtn_event);
			this.logStartsCheck.Toggled += new global::System.EventHandler (this.logStarts_event);
			this.logStopsCheck.Toggled += new global::System.EventHandler (this.logStops_event);
			this.button14.Clicked += new global::System.EventHandler (this.setSpeed_event);
			this.compactWindowOption.Toggled += new global::System.EventHandler (this.windowMode_event);
			this.onTopCheck.Clicked += new global::System.EventHandler (this.onTop_event);
			this.displayStopwatchBtn.Toggled += new global::System.EventHandler (this.displayStopwatch_event);
			this.deleteBtn.Clicked += new global::System.EventHandler (this.deleteClock_event);
			this.closeBtn.Clicked += new global::System.EventHandler (this.closeWindow_event);
		}
	}
}
