
// This file has been generated by the GUI designer. Do not modify.
namespace Chrono
{
	public partial class ClockPropertiesWindow
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.HBox hbox1;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Label label2;
		private global::Gtk.ComboBoxEntry clockNameBox;
		private global::Gtk.Button clockNameBtn;
		private global::Gtk.Notebook detailBook;
		private global::Gtk.Alignment alignment3;
		private global::Gtk.VBox vbox6;
		private global::Gtk.Label label1;
		private global::Gtk.Alignment alignment2;
		private global::Gtk.VBox vbox5;
		private global::Gtk.CheckButton logStartsCheck;
		private global::Gtk.CheckButton logStopsCheck;
		private global::Gtk.HSeparator hseparator1;
		private global::Gtk.Label label3;
		private global::Gtk.Alignment alignment4;
		private global::Gtk.VBox vbox7;
		private global::Gtk.HBox hbox3;
		private global::Gtk.RadioButton tickBackwardOption;
		private global::Gtk.RadioButton tickForwardOption;
		private global::Gtk.HBox hbox4;
		private global::Gtk.HBox hbox7;
		private global::Gtk.SpinButton speedEntry;
		private global::Gtk.Label label4;
		private global::Gtk.Button button14;
		private global::Gtk.HSeparator hseparator3;
		private global::Gtk.Label label5;
		private global::Gtk.Alignment alignment5;
		private global::Gtk.Table table1;
		private global::Gtk.RadioButton compactWindowOption;
		private global::Gtk.ToggleButton displayStopwatchBtn;
		private global::Gtk.CheckButton dockedCheck;
		private global::Gtk.RadioButton normalWindowOption;
		private global::Gtk.CheckButton onTopCheck;
		private global::Gtk.HSeparator hseparator4;
		private global::Gtk.HButtonBox hbuttonbox3;
		private global::Gtk.Button deleteBtn;
		private global::Gtk.Label label;
		private global::Gtk.HButtonBox hbuttonbox2;
		private global::Gtk.Button closeBtn;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Chrono.ClockPropertiesWindow
			this.Name = "Chrono.ClockPropertiesWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Stopwatch Properties");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("Chrono.icon.ico");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(6));
			this.Resizable = false;
			this.AllowGrow = false;
			// Container child Chrono.ClockPropertiesWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 10;
			// Container child hbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 20;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Name");
			this.hbox2.Add (this.label2);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label2]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.clockNameBox = new global::Gtk.ComboBoxEntry ();
			this.clockNameBox.Name = "clockNameBox";
			this.hbox2.Add (this.clockNameBox);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.clockNameBox]));
			w2.Position = 1;
			this.hbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hbox2]));
			w3.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.clockNameBtn = new global::Gtk.Button ();
			this.clockNameBtn.WidthRequest = 80;
			this.clockNameBtn.CanDefault = true;
			this.clockNameBtn.CanFocus = true;
			this.clockNameBtn.Name = "clockNameBtn";
			this.clockNameBtn.UseUnderline = true;
			this.clockNameBtn.Label = global::Mono.Unix.Catalog.GetString ("Create");
			this.hbox1.Add (this.clockNameBtn);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.clockNameBtn]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.detailBook = new global::Gtk.Notebook ();
			this.detailBook.CanFocus = true;
			this.detailBook.Name = "detailBook";
			this.detailBook.CurrentPage = 0;
			this.detailBook.BorderWidth = ((uint)(1));
			// Container child detailBook.Gtk.Notebook+NotebookChild
			this.alignment3 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment3.Name = "alignment3";
			this.alignment3.LeftPadding = ((uint)(24));
			this.alignment3.TopPadding = ((uint)(16));
			this.alignment3.RightPadding = ((uint)(24));
			this.alignment3.BottomPadding = ((uint)(16));
			// Container child alignment3.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 0F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Log the following events");
			this.vbox6.Add (this.label1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.label1]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			this.alignment2.LeftPadding = ((uint)(20));
			this.alignment2.TopPadding = ((uint)(5));
			// Container child alignment2.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.logStartsCheck = new global::Gtk.CheckButton ();
			this.logStartsCheck.CanFocus = true;
			this.logStartsCheck.Name = "logStartsCheck";
			this.logStartsCheck.Label = global::Mono.Unix.Catalog.GetString ("When the Start button is clicked");
			this.logStartsCheck.DrawIndicator = true;
			this.logStartsCheck.UseUnderline = true;
			this.vbox5.Add (this.logStartsCheck);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.logStartsCheck]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.logStopsCheck = new global::Gtk.CheckButton ();
			this.logStopsCheck.CanFocus = true;
			this.logStopsCheck.Name = "logStopsCheck";
			this.logStopsCheck.Label = global::Mono.Unix.Catalog.GetString ("When the Stop button is clicked");
			this.logStopsCheck.DrawIndicator = true;
			this.logStopsCheck.UseUnderline = true;
			this.vbox5.Add (this.logStopsCheck);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.logStopsCheck]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.alignment2.Add (this.vbox5);
			this.vbox6.Add (this.alignment2);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.alignment2]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox6.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hseparator1]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Clock speed settings");
			this.vbox6.Add (this.label3);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.label3]));
			w12.Position = 3;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.alignment4 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment4.Name = "alignment4";
			this.alignment4.LeftPadding = ((uint)(20));
			this.alignment4.TopPadding = ((uint)(5));
			// Container child alignment4.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 20;
			// Container child hbox3.Gtk.Box+BoxChild
			this.tickBackwardOption = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Counting backwards"));
			this.tickBackwardOption.CanFocus = true;
			this.tickBackwardOption.Name = "tickBackwardOption";
			this.tickBackwardOption.Active = true;
			this.tickBackwardOption.DrawIndicator = true;
			this.tickBackwardOption.UseUnderline = true;
			this.tickBackwardOption.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.hbox3.Add (this.tickBackwardOption);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.tickBackwardOption]));
			w13.Position = 0;
			w13.Expand = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.tickForwardOption = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Counting forward"));
			this.tickForwardOption.CanFocus = true;
			this.tickForwardOption.Name = "tickForwardOption";
			this.tickForwardOption.DrawIndicator = true;
			this.tickForwardOption.UseUnderline = true;
			this.tickForwardOption.Group = this.tickBackwardOption.Group;
			this.hbox3.Add (this.tickForwardOption);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.tickForwardOption]));
			w14.Position = 1;
			w14.Expand = false;
			this.vbox7.Add (this.hbox3);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox3]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 10;
			// Container child hbox4.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 20;
			// Container child hbox7.Gtk.Box+BoxChild
			this.speedEntry = new global::Gtk.SpinButton (0, 60, 1);
			this.speedEntry.CanFocus = true;
			this.speedEntry.Name = "speedEntry";
			this.speedEntry.Adjustment.PageIncrement = 6;
			this.speedEntry.ClimbRate = 1;
			this.speedEntry.Digits = ((uint)(2));
			this.speedEntry.Numeric = true;
			this.speedEntry.Value = 1;
			this.hbox7.Add (this.speedEntry);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.speedEntry]));
			w16.PackType = ((global::Gtk.PackType)(1));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Ticking speed");
			this.hbox7.Add (this.label4);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.label4]));
			w17.PackType = ((global::Gtk.PackType)(1));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			this.hbox4.Add (this.hbox7);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.hbox7]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.button14 = new global::Gtk.Button ();
			this.button14.WidthRequest = 40;
			this.button14.CanFocus = true;
			this.button14.Name = "button14";
			this.button14.UseUnderline = true;
			this.button14.Label = global::Mono.Unix.Catalog.GetString ("Apply Speed");
			this.hbox4.Add (this.button14);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.button14]));
			w19.PackType = ((global::Gtk.PackType)(1));
			w19.Position = 1;
			this.vbox7.Add (this.hbox4);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox4]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			this.alignment4.Add (this.vbox7);
			this.vbox6.Add (this.alignment4);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.alignment4]));
			w22.Position = 4;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hseparator3 = new global::Gtk.HSeparator ();
			this.hseparator3.Name = "hseparator3";
			this.vbox6.Add (this.hseparator3);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hseparator3]));
			w23.Position = 5;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.Xalign = 0F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Window settings");
			this.vbox6.Add (this.label5);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.label5]));
			w24.Position = 6;
			w24.Expand = false;
			w24.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.alignment5 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment5.Name = "alignment5";
			this.alignment5.LeftPadding = ((uint)(20));
			this.alignment5.TopPadding = ((uint)(5));
			// Container child alignment5.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(20));
			// Container child table1.Gtk.Table+TableChild
			this.compactWindowOption = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Compact Mode"));
			this.compactWindowOption.CanFocus = true;
			this.compactWindowOption.Name = "compactWindowOption";
			this.compactWindowOption.DrawIndicator = true;
			this.compactWindowOption.UseUnderline = true;
			this.compactWindowOption.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.table1.Add (this.compactWindowOption);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table1 [this.compactWindowOption]));
			w25.TopAttach = ((uint)(1));
			w25.BottomAttach = ((uint)(2));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.displayStopwatchBtn = new global::Gtk.ToggleButton ();
			this.displayStopwatchBtn.CanFocus = true;
			this.displayStopwatchBtn.Name = "displayStopwatchBtn";
			this.displayStopwatchBtn.UseUnderline = true;
			this.displayStopwatchBtn.Label = global::Mono.Unix.Catalog.GetString ("Display");
			this.table1.Add (this.displayStopwatchBtn);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table1 [this.displayStopwatchBtn]));
			w26.TopAttach = ((uint)(2));
			w26.BottomAttach = ((uint)(3));
			w26.RightAttach = ((uint)(2));
			w26.XOptions = ((global::Gtk.AttachOptions)(4));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.dockedCheck = new global::Gtk.CheckButton ();
			this.dockedCheck.CanFocus = true;
			this.dockedCheck.Name = "dockedCheck";
			this.dockedCheck.Label = global::Mono.Unix.Catalog.GetString ("Dock in Log Window");
			this.dockedCheck.DrawIndicator = true;
			this.dockedCheck.UseUnderline = true;
			this.table1.Add (this.dockedCheck);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table1 [this.dockedCheck]));
			w27.TopAttach = ((uint)(1));
			w27.BottomAttach = ((uint)(2));
			w27.LeftAttach = ((uint)(1));
			w27.RightAttach = ((uint)(2));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.normalWindowOption = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Normal Mode"));
			this.normalWindowOption.CanFocus = true;
			this.normalWindowOption.Name = "normalWindowOption";
			this.normalWindowOption.DrawIndicator = true;
			this.normalWindowOption.UseUnderline = true;
			this.normalWindowOption.Group = this.compactWindowOption.Group;
			this.table1.Add (this.normalWindowOption);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table1 [this.normalWindowOption]));
			w28.XOptions = ((global::Gtk.AttachOptions)(4));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.onTopCheck = new global::Gtk.CheckButton ();
			this.onTopCheck.CanFocus = true;
			this.onTopCheck.Name = "onTopCheck";
			this.onTopCheck.Label = global::Mono.Unix.Catalog.GetString ("Display on top");
			this.onTopCheck.DrawIndicator = true;
			this.onTopCheck.UseUnderline = true;
			this.table1.Add (this.onTopCheck);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table1 [this.onTopCheck]));
			w29.LeftAttach = ((uint)(1));
			w29.RightAttach = ((uint)(2));
			w29.XOptions = ((global::Gtk.AttachOptions)(4));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			this.alignment5.Add (this.table1);
			this.vbox6.Add (this.alignment5);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.alignment5]));
			w31.Position = 7;
			w31.Expand = false;
			w31.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hseparator4 = new global::Gtk.HSeparator ();
			this.hseparator4.Name = "hseparator4";
			this.vbox6.Add (this.hseparator4);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hseparator4]));
			w32.Position = 8;
			w32.Expand = false;
			w32.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbuttonbox3 = new global::Gtk.HButtonBox ();
			this.hbuttonbox3.Name = "hbuttonbox3";
			this.hbuttonbox3.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
			// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
			this.deleteBtn = new global::Gtk.Button ();
			this.deleteBtn.CanFocus = true;
			this.deleteBtn.Name = "deleteBtn";
			this.deleteBtn.UseUnderline = true;
			this.deleteBtn.Label = global::Mono.Unix.Catalog.GetString ("Delete");
			this.hbuttonbox3.Add (this.deleteBtn);
			global::Gtk.ButtonBox.ButtonBoxChild w33 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3 [this.deleteBtn]));
			w33.Expand = false;
			w33.Fill = false;
			this.vbox6.Add (this.hbuttonbox3);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbuttonbox3]));
			w34.Position = 9;
			w34.Expand = false;
			w34.Fill = false;
			this.alignment3.Add (this.vbox6);
			this.detailBook.Add (this.alignment3);
			// Notebook tab
			this.label = new global::Gtk.Label ();
			this.label.Name = "label";
			this.label.LabelProp = global::Mono.Unix.Catalog.GetString ("General");
			this.detailBook.SetTabLabel (this.alignment3, this.label);
			this.label.ShowAll ();
			this.vbox2.Add (this.detailBook);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.detailBook]));
			w37.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbuttonbox2 = new global::Gtk.HButtonBox ();
			this.hbuttonbox2.Name = "hbuttonbox2";
			this.hbuttonbox2.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.closeBtn = new global::Gtk.Button ();
			this.closeBtn.CanFocus = true;
			this.closeBtn.Name = "closeBtn";
			this.closeBtn.UseUnderline = true;
			this.closeBtn.Label = global::Mono.Unix.Catalog.GetString ("Close");
			this.hbuttonbox2.Add (this.closeBtn);
			global::Gtk.ButtonBox.ButtonBoxChild w38 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.closeBtn]));
			w38.Expand = false;
			w38.Fill = false;
			this.vbox2.Add (this.hbuttonbox2);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbuttonbox2]));
			w39.PackType = ((global::Gtk.PackType)(1));
			w39.Position = 2;
			w39.Expand = false;
			w39.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 414;
			this.DefaultHeight = 533;
			this.clockNameBtn.HasDefault = true;
			this.Hide ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.windowDelete_event);
			this.clockNameBox.Changed += new global::System.EventHandler (this.clockNameChanged_event);
			this.clockNameBtn.Clicked += new global::System.EventHandler (this.clockNameBtn_event);
			this.logStartsCheck.Toggled += new global::System.EventHandler (this.logStarts_event);
			this.logStopsCheck.Toggled += new global::System.EventHandler (this.logStops_event);
			this.button14.Clicked += new global::System.EventHandler (this.setSpeed_event);
			this.onTopCheck.Toggled += new global::System.EventHandler (this.onTop_event);
			this.dockedCheck.Toggled += new global::System.EventHandler (this.docked_event);
			this.displayStopwatchBtn.Toggled += new global::System.EventHandler (this.displayStopwatch_event);
			this.compactWindowOption.Toggled += new global::System.EventHandler (this.windowMode_event);
			this.deleteBtn.Clicked += new global::System.EventHandler (this.deleteClock_event);
			this.closeBtn.Clicked += new global::System.EventHandler (this.closeWindow_event);
		}
	}
}
