
// This file has been generated by the GUI designer. Do not modify.
namespace Chrono
{
	public partial class StopwatchWindow
	{
		private global::Gtk.HBox hbox1;
		private global::Gtk.Button backwardBtn;
		private global::Gtk.VBox vbox2;
		private global::Gtk.Entry timeDisplayBox;
		private global::Gtk.Button startBtn;
		private global::Gtk.Button forwardBtn;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Chrono.StopwatchWindow
			this.Name = "Chrono.StopwatchWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Stopwatch");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("icon.ico");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.AllowGrow = false;
			// Container child Chrono.StopwatchWindow.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.WidthRequest = 400;
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 2;
			// Container child hbox1.Gtk.Box+BoxChild
			this.backwardBtn = new global::Gtk.Button ();
			this.backwardBtn.WidthRequest = 30;
			this.backwardBtn.CanFocus = true;
			this.backwardBtn.Name = "backwardBtn";
			this.backwardBtn.UseUnderline = true;
			this.backwardBtn.Label = global::Mono.Unix.Catalog.GetString ("<");
			this.hbox1.Add (this.backwardBtn);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.backwardBtn]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 1;
			this.vbox2.BorderWidth = ((uint)(2));
			// Container child vbox2.Gtk.Box+BoxChild
			this.timeDisplayBox = new global::Gtk.Entry ();
			this.timeDisplayBox.CanFocus = true;
			this.timeDisplayBox.Name = "timeDisplayBox";
			this.timeDisplayBox.Text = global::Mono.Unix.Catalog.GetString ("00:00:00.000");
			this.timeDisplayBox.IsEditable = true;
			this.timeDisplayBox.WidthChars = 12;
			this.timeDisplayBox.InvisibleChar = '•';
			this.timeDisplayBox.Xalign = 0.5F;
			this.vbox2.Add (this.timeDisplayBox);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.timeDisplayBox]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.startBtn = new global::Gtk.Button ();
			this.startBtn.CanFocus = true;
			this.startBtn.Name = "startBtn";
			this.startBtn.UseUnderline = true;
			this.startBtn.Label = global::Mono.Unix.Catalog.GetString ("Start");
			this.vbox2.Add (this.startBtn);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.startBtn]));
			w3.PackType = ((global::Gtk.PackType)(1));
			w3.Position = 1;
			this.hbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox2]));
			w4.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.forwardBtn = new global::Gtk.Button ();
			this.forwardBtn.WidthRequest = 30;
			this.forwardBtn.CanFocus = true;
			this.forwardBtn.Name = "forwardBtn";
			this.forwardBtn.UseUnderline = true;
			this.forwardBtn.Label = global::Mono.Unix.Catalog.GetString (">");
			this.hbox1.Add (this.forwardBtn);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.forwardBtn]));
			w5.PackType = ((global::Gtk.PackType)(1));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 402;
			this.DefaultHeight = 90;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.windowDelete_event);
			this.backwardBtn.Clicked += new global::System.EventHandler (this.backwardBtn_event);
			this.timeDisplayBox.Changed += new global::System.EventHandler (this.displayBoxChanged_event);
			this.startBtn.Clicked += new global::System.EventHandler (this.startBtn_event);
			this.forwardBtn.Clicked += new global::System.EventHandler (this.forwardBtn_event);
		}
	}
}
