
// This file has been generated by the GUI designer. Do not modify.
namespace Chrono
{
	public partial class PreferencesWindow
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.Notebook notebook2;
		private global::Gtk.Alignment alignment2;
		private global::Gtk.VBox vbox10;
		private global::Gtk.CheckButton createClockOnStartupCheck;
		private global::Gtk.Alignment alignment4;
		private global::Gtk.VBox vbox12;
		private global::Gtk.HBox hbox6;
		private global::Gtk.Label label5;
		private global::Gtk.Entry firstClockNameEntry;
		private global::Gtk.Label label4;
		private global::Gtk.Alignment alignment1;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Label label7;
		private global::Gtk.Alignment alignment5;
		private global::Gtk.Table table1;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Label label3;
		private global::Gtk.Entry previewDisplayBox;
		private global::Gtk.RadioButton showAbbreviationsOption;
		private global::Gtk.CheckButton showHoursCheck;
		private global::Gtk.CheckButton showLeadingZeroCheck;
		private global::Gtk.CheckButton showMilisecondsCheck;
		private global::Gtk.CheckButton showMinusSymbolCheck;
		private global::Gtk.CheckButton showMinutesCheck;
		private global::Gtk.CheckButton showPlusSymbolCheck;
		private global::Gtk.CheckButton showSecondsCheck;
		private global::Gtk.RadioButton showSeparatorsOption;
		private global::Gtk.HSeparator hseparator3;
		private global::Gtk.Label label8;
		private global::Gtk.Alignment alignment7;
		private global::Gtk.VBox vbox14;
		private global::Gtk.RadioButton normalModeOption;
		private global::Gtk.RadioButton compactModeOption;
		private global::Gtk.Label label2;
		private global::Gtk.HButtonBox hbuttonbox2;
		private global::Gtk.Button button133;
		private global::Gtk.Button button32;
		private global::Gtk.Button button19;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Chrono.PreferencesWindow
			this.Name = "Chrono.PreferencesWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Preferences");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("Chrono.icon.ico");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(6));
			this.Resizable = false;
			// Container child Chrono.PreferencesWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.notebook2 = new global::Gtk.Notebook ();
			this.notebook2.CanFocus = true;
			this.notebook2.Name = "notebook2";
			this.notebook2.CurrentPage = 1;
			this.notebook2.BorderWidth = ((uint)(1));
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			this.alignment2.LeftPadding = ((uint)(24));
			this.alignment2.TopPadding = ((uint)(16));
			this.alignment2.RightPadding = ((uint)(24));
			this.alignment2.BottomPadding = ((uint)(16));
			// Container child alignment2.Gtk.Container+ContainerChild
			this.vbox10 = new global::Gtk.VBox ();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.createClockOnStartupCheck = new global::Gtk.CheckButton ();
			this.createClockOnStartupCheck.CanFocus = true;
			this.createClockOnStartupCheck.Name = "createClockOnStartupCheck";
			this.createClockOnStartupCheck.Label = global::Mono.Unix.Catalog.GetString ("Create a stopwatch on startup");
			this.createClockOnStartupCheck.Active = true;
			this.createClockOnStartupCheck.DrawIndicator = true;
			this.createClockOnStartupCheck.UseUnderline = true;
			this.vbox10.Add (this.createClockOnStartupCheck);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.createClockOnStartupCheck]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.alignment4 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment4.Name = "alignment4";
			this.alignment4.LeftPadding = ((uint)(20));
			this.alignment4.TopPadding = ((uint)(5));
			// Container child alignment4.Gtk.Container+ContainerChild
			this.vbox12 = new global::Gtk.VBox ();
			this.vbox12.Name = "vbox12";
			this.vbox12.Spacing = 6;
			// Container child vbox12.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 20;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Name");
			this.hbox6.Add (this.label5);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label5]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.firstClockNameEntry = new global::Gtk.Entry ();
			this.firstClockNameEntry.CanFocus = true;
			this.firstClockNameEntry.Name = "firstClockNameEntry";
			this.firstClockNameEntry.Text = global::Mono.Unix.Catalog.GetString ("Sundial");
			this.firstClockNameEntry.IsEditable = true;
			this.firstClockNameEntry.InvisibleChar = '●';
			this.hbox6.Add (this.firstClockNameEntry);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.firstClockNameEntry]));
			w3.Position = 1;
			this.vbox12.Add (this.hbox6);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.hbox6]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			this.alignment4.Add (this.vbox12);
			this.vbox10.Add (this.alignment4);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.alignment4]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.alignment2.Add (this.vbox10);
			this.notebook2.Add (this.alignment2);
			// Notebook tab
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Startup");
			this.notebook2.SetTabLabel (this.alignment2, this.label4);
			this.label4.ShowAll ();
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.alignment1.LeftPadding = ((uint)(24));
			this.alignment1.TopPadding = ((uint)(16));
			this.alignment1.RightPadding = ((uint)(24));
			this.alignment1.BottomPadding = ((uint)(16));
			// Container child alignment1.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.Xalign = 0F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Show the following on the time display box");
			this.vbox3.Add (this.label7);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label7]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.alignment5 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment5.Name = "alignment5";
			this.alignment5.LeftPadding = ((uint)(20));
			this.alignment5.TopPadding = ((uint)(5));
			// Container child alignment5.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(4)), ((uint)(3)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(20));
			// Container child table1.Gtk.Table+TableChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 20;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Preview");
			this.hbox1.Add (this.label3);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label3]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.previewDisplayBox = new global::Gtk.Entry ();
			this.previewDisplayBox.Sensitive = false;
			this.previewDisplayBox.CanFocus = true;
			this.previewDisplayBox.Name = "previewDisplayBox";
			this.previewDisplayBox.Text = "03:14:15.926";
			this.previewDisplayBox.IsEditable = false;
			this.previewDisplayBox.WidthChars = 16;
			this.previewDisplayBox.InvisibleChar = '●';
			this.previewDisplayBox.Xalign = 1F;
			this.hbox1.Add (this.previewDisplayBox);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.previewDisplayBox]));
			w11.Position = 1;
			this.table1.Add (this.hbox1);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this.hbox1]));
			w12.TopAttach = ((uint)(3));
			w12.BottomAttach = ((uint)(4));
			w12.RightAttach = ((uint)(2));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.showAbbreviationsOption = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Abbreviations"));
			this.showAbbreviationsOption.CanFocus = true;
			this.showAbbreviationsOption.Name = "showAbbreviationsOption";
			this.showAbbreviationsOption.DrawIndicator = true;
			this.showAbbreviationsOption.UseUnderline = true;
			this.showAbbreviationsOption.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.table1.Add (this.showAbbreviationsOption);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1 [this.showAbbreviationsOption]));
			w13.TopAttach = ((uint)(2));
			w13.BottomAttach = ((uint)(3));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.showHoursCheck = new global::Gtk.CheckButton ();
			this.showHoursCheck.CanFocus = true;
			this.showHoursCheck.Name = "showHoursCheck";
			this.showHoursCheck.Label = global::Mono.Unix.Catalog.GetString ("Hours");
			this.showHoursCheck.Active = true;
			this.showHoursCheck.DrawIndicator = true;
			this.showHoursCheck.UseUnderline = true;
			this.table1.Add (this.showHoursCheck);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1 [this.showHoursCheck]));
			w14.LeftAttach = ((uint)(2));
			w14.RightAttach = ((uint)(3));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.showLeadingZeroCheck = new global::Gtk.CheckButton ();
			this.showLeadingZeroCheck.CanFocus = true;
			this.showLeadingZeroCheck.Name = "showLeadingZeroCheck";
			this.showLeadingZeroCheck.Label = global::Mono.Unix.Catalog.GetString ("Leading Zero");
			this.showLeadingZeroCheck.Active = true;
			this.showLeadingZeroCheck.DrawIndicator = true;
			this.showLeadingZeroCheck.UseUnderline = true;
			this.table1.Add (this.showLeadingZeroCheck);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1 [this.showLeadingZeroCheck]));
			w15.LeftAttach = ((uint)(1));
			w15.RightAttach = ((uint)(2));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.showMilisecondsCheck = new global::Gtk.CheckButton ();
			this.showMilisecondsCheck.CanFocus = true;
			this.showMilisecondsCheck.Name = "showMilisecondsCheck";
			this.showMilisecondsCheck.Label = global::Mono.Unix.Catalog.GetString ("Miliseconds");
			this.showMilisecondsCheck.Active = true;
			this.showMilisecondsCheck.DrawIndicator = true;
			this.showMilisecondsCheck.UseUnderline = true;
			this.table1.Add (this.showMilisecondsCheck);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1 [this.showMilisecondsCheck]));
			w16.TopAttach = ((uint)(3));
			w16.BottomAttach = ((uint)(4));
			w16.LeftAttach = ((uint)(2));
			w16.RightAttach = ((uint)(3));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.showMinusSymbolCheck = new global::Gtk.CheckButton ();
			this.showMinusSymbolCheck.CanFocus = true;
			this.showMinusSymbolCheck.Name = "showMinusSymbolCheck";
			this.showMinusSymbolCheck.Label = global::Mono.Unix.Catalog.GetString ("Minus Symbol");
			this.showMinusSymbolCheck.Active = true;
			this.showMinusSymbolCheck.DrawIndicator = true;
			this.showMinusSymbolCheck.UseUnderline = true;
			this.table1.Add (this.showMinusSymbolCheck);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1 [this.showMinusSymbolCheck]));
			w17.TopAttach = ((uint)(1));
			w17.BottomAttach = ((uint)(2));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.showMinutesCheck = new global::Gtk.CheckButton ();
			this.showMinutesCheck.CanFocus = true;
			this.showMinutesCheck.Name = "showMinutesCheck";
			this.showMinutesCheck.Label = global::Mono.Unix.Catalog.GetString ("Minutes");
			this.showMinutesCheck.Active = true;
			this.showMinutesCheck.DrawIndicator = true;
			this.showMinutesCheck.UseUnderline = true;
			this.table1.Add (this.showMinutesCheck);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1 [this.showMinutesCheck]));
			w18.TopAttach = ((uint)(1));
			w18.BottomAttach = ((uint)(2));
			w18.LeftAttach = ((uint)(2));
			w18.RightAttach = ((uint)(3));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.showPlusSymbolCheck = new global::Gtk.CheckButton ();
			this.showPlusSymbolCheck.CanFocus = true;
			this.showPlusSymbolCheck.Name = "showPlusSymbolCheck";
			this.showPlusSymbolCheck.Label = global::Mono.Unix.Catalog.GetString ("Plus Symbol");
			this.showPlusSymbolCheck.DrawIndicator = true;
			this.showPlusSymbolCheck.UseUnderline = true;
			this.table1.Add (this.showPlusSymbolCheck);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1 [this.showPlusSymbolCheck]));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.showSecondsCheck = new global::Gtk.CheckButton ();
			this.showSecondsCheck.CanFocus = true;
			this.showSecondsCheck.Name = "showSecondsCheck";
			this.showSecondsCheck.Label = global::Mono.Unix.Catalog.GetString ("Seconds");
			this.showSecondsCheck.Active = true;
			this.showSecondsCheck.DrawIndicator = true;
			this.showSecondsCheck.UseUnderline = true;
			this.table1.Add (this.showSecondsCheck);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table1 [this.showSecondsCheck]));
			w20.TopAttach = ((uint)(2));
			w20.BottomAttach = ((uint)(3));
			w20.LeftAttach = ((uint)(2));
			w20.RightAttach = ((uint)(3));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.showSeparatorsOption = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Separators"));
			this.showSeparatorsOption.CanFocus = true;
			this.showSeparatorsOption.Name = "showSeparatorsOption";
			this.showSeparatorsOption.DrawIndicator = true;
			this.showSeparatorsOption.UseUnderline = true;
			this.showSeparatorsOption.Group = this.showAbbreviationsOption.Group;
			this.table1.Add (this.showSeparatorsOption);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table1 [this.showSeparatorsOption]));
			w21.TopAttach = ((uint)(1));
			w21.BottomAttach = ((uint)(2));
			w21.LeftAttach = ((uint)(1));
			w21.RightAttach = ((uint)(2));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			this.alignment5.Add (this.table1);
			this.vbox3.Add (this.alignment5);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.alignment5]));
			w23.Position = 1;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hseparator3 = new global::Gtk.HSeparator ();
			this.hseparator3.Name = "hseparator3";
			this.vbox3.Add (this.hseparator3);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hseparator3]));
			w24.Position = 2;
			w24.Expand = false;
			w24.Fill = false;
			w24.Padding = ((uint)(5));
			// Container child vbox3.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.Xalign = 0F;
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("When created, stopwatch windows are");
			this.vbox3.Add (this.label8);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label8]));
			w25.Position = 3;
			w25.Expand = false;
			w25.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.alignment7 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment7.Name = "alignment7";
			this.alignment7.LeftPadding = ((uint)(20));
			// Container child alignment7.Gtk.Container+ContainerChild
			this.vbox14 = new global::Gtk.VBox ();
			this.vbox14.Name = "vbox14";
			this.vbox14.Spacing = 6;
			// Container child vbox14.Gtk.Box+BoxChild
			this.normalModeOption = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Normal, with buttons for toggling countdown"));
			this.normalModeOption.CanFocus = true;
			this.normalModeOption.Name = "normalModeOption";
			this.normalModeOption.DrawIndicator = true;
			this.normalModeOption.UseUnderline = true;
			this.normalModeOption.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.vbox14.Add (this.normalModeOption);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.normalModeOption]));
			w26.Position = 0;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vbox14.Gtk.Box+BoxChild
			this.compactModeOption = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Compact, with smaller display and icon buttons"));
			this.compactModeOption.CanFocus = true;
			this.compactModeOption.Name = "compactModeOption";
			this.compactModeOption.DrawIndicator = true;
			this.compactModeOption.UseUnderline = true;
			this.compactModeOption.Group = this.normalModeOption.Group;
			this.vbox14.Add (this.compactModeOption);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.compactModeOption]));
			w27.Position = 1;
			w27.Expand = false;
			w27.Fill = false;
			this.alignment7.Add (this.vbox14);
			this.vbox3.Add (this.alignment7);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.alignment7]));
			w29.Position = 4;
			w29.Expand = false;
			w29.Fill = false;
			this.alignment1.Add (this.vbox3);
			this.notebook2.Add (this.alignment1);
			global::Gtk.Notebook.NotebookChild w31 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.alignment1]));
			w31.Position = 1;
			// Notebook tab
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Stopwatch");
			this.notebook2.SetTabLabel (this.alignment1, this.label2);
			this.label2.ShowAll ();
			this.vbox2.Add (this.notebook2);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.notebook2]));
			w32.Position = 0;
			w32.Expand = false;
			w32.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbuttonbox2 = new global::Gtk.HButtonBox ();
			this.hbuttonbox2.Name = "hbuttonbox2";
			this.hbuttonbox2.Spacing = 4;
			this.hbuttonbox2.BorderWidth = ((uint)(4));
			this.hbuttonbox2.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.button133 = new global::Gtk.Button ();
			this.button133.CanFocus = true;
			this.button133.Name = "button133";
			this.button133.UseStock = true;
			this.button133.UseUnderline = true;
			this.button133.Label = "gtk-apply";
			this.hbuttonbox2.Add (this.button133);
			global::Gtk.ButtonBox.ButtonBoxChild w33 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.button133]));
			w33.Expand = false;
			w33.Fill = false;
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.button32 = new global::Gtk.Button ();
			this.button32.CanFocus = true;
			this.button32.Name = "button32";
			this.button32.UseStock = true;
			this.button32.UseUnderline = true;
			this.button32.Label = "gtk-cancel";
			this.hbuttonbox2.Add (this.button32);
			global::Gtk.ButtonBox.ButtonBoxChild w34 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.button32]));
			w34.Position = 1;
			w34.Expand = false;
			w34.Fill = false;
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.button19 = new global::Gtk.Button ();
			this.button19.CanFocus = true;
			this.button19.Name = "button19";
			this.button19.UseStock = true;
			this.button19.UseUnderline = true;
			this.button19.Label = "gtk-ok";
			this.hbuttonbox2.Add (this.button19);
			global::Gtk.ButtonBox.ButtonBoxChild w35 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.button19]));
			w35.Position = 2;
			w35.Expand = false;
			w35.Fill = false;
			this.vbox2.Add (this.hbuttonbox2);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbuttonbox2]));
			w36.Position = 1;
			w36.Expand = false;
			w36.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 459;
			this.DefaultHeight = 440;
			this.Hide ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.WindowDelete_event);
			this.Shown += new global::System.EventHandler (this.WindowShown_event);
			this.showSeparatorsOption.Toggled += new global::System.EventHandler (this.displayCheckToggled_event);
			this.showSecondsCheck.Toggled += new global::System.EventHandler (this.displayCheckToggled_event);
			this.showPlusSymbolCheck.Toggled += new global::System.EventHandler (this.displayCheckToggled_event);
			this.showMinutesCheck.Toggled += new global::System.EventHandler (this.displayCheckToggled_event);
			this.showMinusSymbolCheck.Toggled += new global::System.EventHandler (this.displayCheckToggled_event);
			this.showMilisecondsCheck.Toggled += new global::System.EventHandler (this.displayCheckToggled_event);
			this.showLeadingZeroCheck.Toggled += new global::System.EventHandler (this.displayCheckToggled_event);
			this.showHoursCheck.Toggled += new global::System.EventHandler (this.displayCheckToggled_event);
			this.showAbbreviationsOption.Toggled += new global::System.EventHandler (this.displayCheckToggled_event);
			this.button133.Clicked += new global::System.EventHandler (this.apply_event);
			this.button32.Clicked += new global::System.EventHandler (this.cancel_event);
			this.button19.Clicked += new global::System.EventHandler (this.ok_event);
		}
	}
}
