
// This file has been generated by the GUI designer. Do not modify.
namespace Chrono
{
	public partial class PreferencesWindow
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.Notebook notebook2;
		private global::Gtk.Alignment alignment2;
		private global::Gtk.VBox vbox10;
		private global::Gtk.CheckButton createWatchOnStartupCheck;
		private global::Gtk.Alignment alignment4;
		private global::Gtk.VBox vbox12;
		private global::Gtk.HBox startupClockNameContainer;
		private global::Gtk.Label startupClockNameLabel;
		private global::Gtk.Entry startupClockNameEntry;
		private global::Gtk.HSeparator hseparator3;
		private global::Gtk.Label byDefaultLabel;
		private global::Gtk.Alignment alignment6;
		private global::Gtk.VBox vbox13;
		private global::Gtk.HBox hbox3;
		private global::Gtk.CheckButton compactByDefaultCheck;
		private global::Gtk.CheckButton dockedByDefaultCheck;
		private global::Gtk.Label generalTabLabel;
		private global::Gtk.Alignment alignment1;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Label formattingTopLabel;
		private global::Gtk.Alignment alignment5;
		private global::Gtk.Table table1;
		private global::Gtk.RadioButton showAbbreviationsOption;
		private global::Gtk.CheckButton showHoursCheck;
		private global::Gtk.CheckButton showLeadingZerosCheck;
		private global::Gtk.CheckButton showMillisecondsCheck;
		private global::Gtk.CheckButton showMinusSymbolCheck;
		private global::Gtk.CheckButton showMinutesCheck;
		private global::Gtk.CheckButton showPlusSymbolCheck;
		private global::Gtk.CheckButton showSecondsCheck;
		private global::Gtk.RadioButton showSeparatorsOption;
		private global::Gtk.HBox previewContainer;
		private global::Gtk.Label previewLabel;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Entry previewDisplayBox1;
		private global::Gtk.Entry previewDisplayBox2;
		private global::Gtk.HSeparator hseparator5;
		private global::Gtk.Label formattingTabLabel;
		private global::Gtk.HButtonBox hbuttonbox2;
		private global::Gtk.Button button133;
		private global::Gtk.Button button32;
		private global::Gtk.Button button19;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Chrono.PreferencesWindow
			this.Name = "Chrono.PreferencesWindow";
			this.Title = "Preferences";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(6));
			this.Resizable = false;
			// Container child Chrono.PreferencesWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.notebook2 = new global::Gtk.Notebook ();
			this.notebook2.CanFocus = true;
			this.notebook2.Name = "notebook2";
			this.notebook2.CurrentPage = 1;
			this.notebook2.BorderWidth = ((uint)(1));
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			this.alignment2.LeftPadding = ((uint)(24));
			this.alignment2.TopPadding = ((uint)(16));
			this.alignment2.RightPadding = ((uint)(24));
			this.alignment2.BottomPadding = ((uint)(16));
			// Container child alignment2.Gtk.Container+ContainerChild
			this.vbox10 = new global::Gtk.VBox ();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.createWatchOnStartupCheck = new global::Gtk.CheckButton ();
			this.createWatchOnStartupCheck.CanFocus = true;
			this.createWatchOnStartupCheck.Name = "createWatchOnStartupCheck";
			this.createWatchOnStartupCheck.Label = "Create a stopwatch on startup";
			this.createWatchOnStartupCheck.Active = true;
			this.createWatchOnStartupCheck.DrawIndicator = true;
			this.createWatchOnStartupCheck.UseUnderline = true;
			this.vbox10.Add (this.createWatchOnStartupCheck);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.createWatchOnStartupCheck]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.alignment4 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment4.Name = "alignment4";
			this.alignment4.LeftPadding = ((uint)(20));
			this.alignment4.TopPadding = ((uint)(5));
			// Container child alignment4.Gtk.Container+ContainerChild
			this.vbox12 = new global::Gtk.VBox ();
			this.vbox12.Name = "vbox12";
			this.vbox12.Spacing = 6;
			// Container child vbox12.Gtk.Box+BoxChild
			this.startupClockNameContainer = new global::Gtk.HBox ();
			this.startupClockNameContainer.Name = "startupClockNameContainer";
			this.startupClockNameContainer.Spacing = 20;
			// Container child startupClockNameContainer.Gtk.Box+BoxChild
			this.startupClockNameLabel = new global::Gtk.Label ();
			this.startupClockNameLabel.Name = "startupClockNameLabel";
			this.startupClockNameLabel.LabelProp = "Name";
			this.startupClockNameContainer.Add (this.startupClockNameLabel);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.startupClockNameContainer [this.startupClockNameLabel]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child startupClockNameContainer.Gtk.Box+BoxChild
			this.startupClockNameEntry = new global::Gtk.Entry ();
			this.startupClockNameEntry.CanFocus = true;
			this.startupClockNameEntry.Name = "startupClockNameEntry";
			this.startupClockNameEntry.Text = "Insert name here";
			this.startupClockNameEntry.IsEditable = true;
			this.startupClockNameEntry.InvisibleChar = '●';
			this.startupClockNameContainer.Add (this.startupClockNameEntry);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.startupClockNameContainer [this.startupClockNameEntry]));
			w3.Position = 1;
			this.vbox12.Add (this.startupClockNameContainer);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.startupClockNameContainer]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			this.alignment4.Add (this.vbox12);
			this.vbox10.Add (this.alignment4);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.alignment4]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hseparator3 = new global::Gtk.HSeparator ();
			this.hseparator3.Name = "hseparator3";
			this.vbox10.Add (this.hseparator3);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.hseparator3]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.byDefaultLabel = new global::Gtk.Label ();
			this.byDefaultLabel.Name = "byDefaultLabel";
			this.byDefaultLabel.Xalign = 0F;
			this.byDefaultLabel.LabelProp = "By default stopwatches are";
			this.vbox10.Add (this.byDefaultLabel);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.byDefaultLabel]));
			w8.Position = 3;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.alignment6 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment6.Name = "alignment6";
			this.alignment6.LeftPadding = ((uint)(20));
			this.alignment6.TopPadding = ((uint)(5));
			// Container child alignment6.Gtk.Container+ContainerChild
			this.vbox13 = new global::Gtk.VBox ();
			this.vbox13.Name = "vbox13";
			this.vbox13.Spacing = 6;
			// Container child vbox13.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.compactByDefaultCheck = new global::Gtk.CheckButton ();
			this.compactByDefaultCheck.CanFocus = true;
			this.compactByDefaultCheck.Name = "compactByDefaultCheck";
			this.compactByDefaultCheck.Label = "Compact";
			this.compactByDefaultCheck.DrawIndicator = true;
			this.compactByDefaultCheck.UseUnderline = true;
			this.hbox3.Add (this.compactByDefaultCheck);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.compactByDefaultCheck]));
			w9.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.dockedByDefaultCheck = new global::Gtk.CheckButton ();
			this.dockedByDefaultCheck.CanFocus = true;
			this.dockedByDefaultCheck.Name = "dockedByDefaultCheck";
			this.dockedByDefaultCheck.Label = "Docked";
			this.dockedByDefaultCheck.DrawIndicator = true;
			this.dockedByDefaultCheck.UseUnderline = true;
			this.hbox3.Add (this.dockedByDefaultCheck);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.dockedByDefaultCheck]));
			w10.Position = 1;
			this.vbox13.Add (this.hbox3);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.hbox3]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			this.alignment6.Add (this.vbox13);
			this.vbox10.Add (this.alignment6);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.alignment6]));
			w13.Position = 4;
			w13.Expand = false;
			w13.Fill = false;
			this.alignment2.Add (this.vbox10);
			this.notebook2.Add (this.alignment2);
			// Notebook tab
			this.generalTabLabel = new global::Gtk.Label ();
			this.generalTabLabel.Name = "generalTabLabel";
			this.generalTabLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("General");
			this.notebook2.SetTabLabel (this.alignment2, this.generalTabLabel);
			this.generalTabLabel.ShowAll ();
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.alignment1.LeftPadding = ((uint)(24));
			this.alignment1.TopPadding = ((uint)(16));
			this.alignment1.RightPadding = ((uint)(24));
			this.alignment1.BottomPadding = ((uint)(16));
			// Container child alignment1.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.formattingTopLabel = new global::Gtk.Label ();
			this.formattingTopLabel.Name = "formattingTopLabel";
			this.formattingTopLabel.Xalign = 0F;
			this.formattingTopLabel.LabelProp = "Show the following in the stopwatch display";
			this.vbox3.Add (this.formattingTopLabel);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.formattingTopLabel]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.alignment5 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment5.Name = "alignment5";
			this.alignment5.LeftPadding = ((uint)(20));
			this.alignment5.TopPadding = ((uint)(5));
			// Container child alignment5.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(5)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(20));
			// Container child table1.Gtk.Table+TableChild
			this.showAbbreviationsOption = new global::Gtk.RadioButton ("Abbreviations");
			this.showAbbreviationsOption.CanFocus = true;
			this.showAbbreviationsOption.Name = "showAbbreviationsOption";
			this.showAbbreviationsOption.DrawIndicator = true;
			this.showAbbreviationsOption.UseUnderline = true;
			this.showAbbreviationsOption.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.table1.Add (this.showAbbreviationsOption);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1 [this.showAbbreviationsOption]));
			w17.TopAttach = ((uint)(4));
			w17.BottomAttach = ((uint)(5));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.showHoursCheck = new global::Gtk.CheckButton ();
			this.showHoursCheck.CanFocus = true;
			this.showHoursCheck.Name = "showHoursCheck";
			this.showHoursCheck.Label = "Hours";
			this.showHoursCheck.Active = true;
			this.showHoursCheck.DrawIndicator = true;
			this.showHoursCheck.UseUnderline = true;
			this.table1.Add (this.showHoursCheck);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1 [this.showHoursCheck]));
			w18.TopAttach = ((uint)(1));
			w18.BottomAttach = ((uint)(2));
			w18.LeftAttach = ((uint)(1));
			w18.RightAttach = ((uint)(2));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.showLeadingZerosCheck = new global::Gtk.CheckButton ();
			this.showLeadingZerosCheck.CanFocus = true;
			this.showLeadingZerosCheck.Name = "showLeadingZerosCheck";
			this.showLeadingZerosCheck.Label = "Leading Zeros";
			this.showLeadingZerosCheck.Active = true;
			this.showLeadingZerosCheck.DrawIndicator = true;
			this.showLeadingZerosCheck.UseUnderline = true;
			this.table1.Add (this.showLeadingZerosCheck);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1 [this.showLeadingZerosCheck]));
			w19.LeftAttach = ((uint)(1));
			w19.RightAttach = ((uint)(2));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.showMillisecondsCheck = new global::Gtk.CheckButton ();
			this.showMillisecondsCheck.CanFocus = true;
			this.showMillisecondsCheck.Name = "showMillisecondsCheck";
			this.showMillisecondsCheck.Label = "Milliseconds";
			this.showMillisecondsCheck.Active = true;
			this.showMillisecondsCheck.DrawIndicator = true;
			this.showMillisecondsCheck.UseUnderline = true;
			this.table1.Add (this.showMillisecondsCheck);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table1 [this.showMillisecondsCheck]));
			w20.TopAttach = ((uint)(4));
			w20.BottomAttach = ((uint)(5));
			w20.LeftAttach = ((uint)(1));
			w20.RightAttach = ((uint)(2));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.showMinusSymbolCheck = new global::Gtk.CheckButton ();
			this.showMinusSymbolCheck.CanFocus = true;
			this.showMinusSymbolCheck.Name = "showMinusSymbolCheck";
			this.showMinusSymbolCheck.Label = "Minus Symbol";
			this.showMinusSymbolCheck.Active = true;
			this.showMinusSymbolCheck.DrawIndicator = true;
			this.showMinusSymbolCheck.UseUnderline = true;
			this.table1.Add (this.showMinusSymbolCheck);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table1 [this.showMinusSymbolCheck]));
			w21.TopAttach = ((uint)(1));
			w21.BottomAttach = ((uint)(2));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.showMinutesCheck = new global::Gtk.CheckButton ();
			this.showMinutesCheck.CanFocus = true;
			this.showMinutesCheck.Name = "showMinutesCheck";
			this.showMinutesCheck.Label = "Minutes";
			this.showMinutesCheck.Active = true;
			this.showMinutesCheck.DrawIndicator = true;
			this.showMinutesCheck.UseUnderline = true;
			this.table1.Add (this.showMinutesCheck);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table1 [this.showMinutesCheck]));
			w22.TopAttach = ((uint)(2));
			w22.BottomAttach = ((uint)(3));
			w22.LeftAttach = ((uint)(1));
			w22.RightAttach = ((uint)(2));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.showPlusSymbolCheck = new global::Gtk.CheckButton ();
			this.showPlusSymbolCheck.CanFocus = true;
			this.showPlusSymbolCheck.Name = "showPlusSymbolCheck";
			this.showPlusSymbolCheck.Label = "Plus Symbol";
			this.showPlusSymbolCheck.DrawIndicator = true;
			this.showPlusSymbolCheck.UseUnderline = true;
			this.table1.Add (this.showPlusSymbolCheck);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table1 [this.showPlusSymbolCheck]));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.showSecondsCheck = new global::Gtk.CheckButton ();
			this.showSecondsCheck.CanFocus = true;
			this.showSecondsCheck.Name = "showSecondsCheck";
			this.showSecondsCheck.Label = "Seconds";
			this.showSecondsCheck.Active = true;
			this.showSecondsCheck.DrawIndicator = true;
			this.showSecondsCheck.UseUnderline = true;
			this.table1.Add (this.showSecondsCheck);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table1 [this.showSecondsCheck]));
			w24.TopAttach = ((uint)(3));
			w24.BottomAttach = ((uint)(4));
			w24.LeftAttach = ((uint)(1));
			w24.RightAttach = ((uint)(2));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.showSeparatorsOption = new global::Gtk.RadioButton ("Separators");
			this.showSeparatorsOption.CanFocus = true;
			this.showSeparatorsOption.Name = "showSeparatorsOption";
			this.showSeparatorsOption.DrawIndicator = true;
			this.showSeparatorsOption.UseUnderline = true;
			this.showSeparatorsOption.Group = this.showAbbreviationsOption.Group;
			this.table1.Add (this.showSeparatorsOption);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table1 [this.showSeparatorsOption]));
			w25.TopAttach = ((uint)(3));
			w25.BottomAttach = ((uint)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			this.alignment5.Add (this.table1);
			this.vbox3.Add (this.alignment5);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.alignment5]));
			w27.Position = 1;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.previewContainer = new global::Gtk.HBox ();
			this.previewContainer.Name = "previewContainer";
			this.previewContainer.Spacing = 20;
			// Container child previewContainer.Gtk.Box+BoxChild
			this.previewLabel = new global::Gtk.Label ();
			this.previewLabel.Name = "previewLabel";
			this.previewLabel.Xalign = 0F;
			this.previewLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Preview");
			this.previewContainer.Add (this.previewLabel);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.previewContainer [this.previewLabel]));
			w28.Position = 0;
			w28.Expand = false;
			w28.Fill = false;
			// Container child previewContainer.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.previewDisplayBox1 = new global::Gtk.Entry ();
			this.previewDisplayBox1.Sensitive = false;
			this.previewDisplayBox1.CanFocus = true;
			this.previewDisplayBox1.Name = "previewDisplayBox1";
			this.previewDisplayBox1.Text = "113:59:15.250";
			this.previewDisplayBox1.IsEditable = false;
			this.previewDisplayBox1.WidthChars = 16;
			this.previewDisplayBox1.InvisibleChar = '●';
			this.previewDisplayBox1.Xalign = 1F;
			this.hbox2.Add (this.previewDisplayBox1);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.previewDisplayBox1]));
			w29.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.previewDisplayBox2 = new global::Gtk.Entry ();
			this.previewDisplayBox2.Sensitive = false;
			this.previewDisplayBox2.CanFocus = true;
			this.previewDisplayBox2.Name = "previewDisplayBox2";
			this.previewDisplayBox2.Text = "-00:03:14:159";
			this.previewDisplayBox2.IsEditable = false;
			this.previewDisplayBox2.WidthChars = 16;
			this.previewDisplayBox2.InvisibleChar = '●';
			this.previewDisplayBox2.Xalign = 1F;
			this.hbox2.Add (this.previewDisplayBox2);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.previewDisplayBox2]));
			w30.Position = 1;
			this.previewContainer.Add (this.hbox2);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.previewContainer [this.hbox2]));
			w31.Position = 1;
			this.vbox3.Add (this.previewContainer);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.previewContainer]));
			w32.PackType = ((global::Gtk.PackType)(1));
			w32.Position = 2;
			w32.Expand = false;
			w32.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hseparator5 = new global::Gtk.HSeparator ();
			this.hseparator5.Name = "hseparator5";
			this.vbox3.Add (this.hseparator5);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hseparator5]));
			w33.PackType = ((global::Gtk.PackType)(1));
			w33.Position = 3;
			w33.Expand = false;
			w33.Fill = false;
			this.alignment1.Add (this.vbox3);
			this.notebook2.Add (this.alignment1);
			global::Gtk.Notebook.NotebookChild w35 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.alignment1]));
			w35.Position = 1;
			// Notebook tab
			this.formattingTabLabel = new global::Gtk.Label ();
			this.formattingTabLabel.Name = "formattingTabLabel";
			this.formattingTabLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Formatting");
			this.notebook2.SetTabLabel (this.alignment1, this.formattingTabLabel);
			this.formattingTabLabel.ShowAll ();
			this.vbox2.Add (this.notebook2);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.notebook2]));
			w36.Position = 0;
			w36.Expand = false;
			w36.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbuttonbox2 = new global::Gtk.HButtonBox ();
			this.hbuttonbox2.Name = "hbuttonbox2";
			this.hbuttonbox2.Spacing = 4;
			this.hbuttonbox2.BorderWidth = ((uint)(4));
			this.hbuttonbox2.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.button133 = new global::Gtk.Button ();
			this.button133.CanFocus = true;
			this.button133.Name = "button133";
			this.button133.UseStock = true;
			this.button133.UseUnderline = true;
			this.button133.Label = "gtk-apply";
			this.hbuttonbox2.Add (this.button133);
			global::Gtk.ButtonBox.ButtonBoxChild w37 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.button133]));
			w37.Expand = false;
			w37.Fill = false;
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.button32 = new global::Gtk.Button ();
			this.button32.CanFocus = true;
			this.button32.Name = "button32";
			this.button32.UseStock = true;
			this.button32.UseUnderline = true;
			this.button32.Label = "gtk-cancel";
			this.hbuttonbox2.Add (this.button32);
			global::Gtk.ButtonBox.ButtonBoxChild w38 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.button32]));
			w38.Position = 1;
			w38.Expand = false;
			w38.Fill = false;
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.button19 = new global::Gtk.Button ();
			this.button19.CanFocus = true;
			this.button19.Name = "button19";
			this.button19.UseStock = true;
			this.button19.UseUnderline = true;
			this.button19.Label = "gtk-ok";
			this.hbuttonbox2.Add (this.button19);
			global::Gtk.ButtonBox.ButtonBoxChild w39 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.button19]));
			w39.Position = 2;
			w39.Expand = false;
			w39.Fill = false;
			this.vbox2.Add (this.hbuttonbox2);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbuttonbox2]));
			w40.Position = 1;
			w40.Expand = false;
			w40.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 341;
			this.DefaultHeight = 362;
			this.Hide ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.windowDelete_event);
			this.Shown += new global::System.EventHandler (this.windowShown_event);
			this.createWatchOnStartupCheck.Toggled += new global::System.EventHandler (this.createOnStartupToggled_event);
			this.showSeparatorsOption.Toggled += new global::System.EventHandler (this.displayCheckToggled_event);
			this.showSecondsCheck.Toggled += new global::System.EventHandler (this.displayCheckToggled_event);
			this.showPlusSymbolCheck.Toggled += new global::System.EventHandler (this.displayCheckToggled_event);
			this.showMinutesCheck.Toggled += new global::System.EventHandler (this.displayCheckToggled_event);
			this.showMinusSymbolCheck.Toggled += new global::System.EventHandler (this.displayCheckToggled_event);
			this.showMillisecondsCheck.Toggled += new global::System.EventHandler (this.displayCheckToggled_event);
			this.showLeadingZerosCheck.Toggled += new global::System.EventHandler (this.displayCheckToggled_event);
			this.showHoursCheck.Toggled += new global::System.EventHandler (this.displayCheckToggled_event);
			this.showAbbreviationsOption.Toggled += new global::System.EventHandler (this.displayCheckToggled_event);
			this.button133.Clicked += new global::System.EventHandler (this.apply_event);
			this.button32.Clicked += new global::System.EventHandler (this.cancel_event);
			this.button19.Clicked += new global::System.EventHandler (this.ok_event);
		}
	}
}
